"""Amenity profiles for each property in the comp set.

Keyed by property slug. Data sourced from property websites via Gemini research
(May 2026). Used by the pricing algorithm to compute quality scores and
amenity adjustments.
"""

AMENITIES: dict[str, dict] = {
    "inspire-west-town": {
        "building_amenities": [
            "Sky Lounge", "Sky Terrace", "Peloton Studio", "Yoga Room",
            "Work-from-home Lounge", "Catering Kitchen", "Fire Pits",
            "Grilling Stations", "Package Room", "Bike Storage",
            "Dog Run", "Pet Spa",
        ],
        "unit_features": [
            "Bosch/Thermador appliances", "Quartz countertops", "Gas ranges",
            "Floor-to-ceiling windows", "In-unit W/D", "Smart thermostats",
            "Blackout shades", "Hardwood flooring", "Keyless entry",
        ],
        "parking_type": "Heated garage",
        "pet_friendly": True,
        "doorman_concierge": True,
        "pool": False,
        "rooftop": True,
        "fitness": "Premium/Peloton + Yoga",
    },
    "aberdeen-crossing": {
        "building_amenities": [
            "Rooftop deck", "Grilling stations", "Fire pits",
            "Resident lounge", "Private offices", "Conference room",
            "Coffee bar",
        ],
        "unit_features": [
            "Stainless appliances", "In-unit W/D", "Large closets",
            "Modern flooring", "Select balconies",
        ],
        "parking_type": "Detached garage",
        "pet_friendly": True,
        "doorman_concierge": False,
        "pool": False,
        "rooftop": True,
        "fitness": "Basic",
    },
    "nevele22": {
        "building_amenities": [
            "8th floor rooftop", "Outdoor kitchen", "Bioclimatic Pergola",
            "Fire pits", "Bike repair station", "Dog run",
            "Luxor package lockers", "CTA Transit Tracker",
        ],
        "unit_features": [
            "Fisher & Paykel appliances", "Waterfall quartz islands",
            "Salto keyless entry", "EcoSmart thermostats",
            "LVT plank flooring", "Solar shades",
        ],
        "parking_type": "Garage",
        "pet_friendly": True,
        "doorman_concierge": False,
        "pool": False,
        "rooftop": True,
        "fitness": "Basic + Outdoor Yoga Deck",
    },
    "seven-10-west": {
        "building_amenities": [
            "Rooftop deck", "Outdoor TV", "Fire pit",
            "Co-working lounge", "Conference room", "Dog run",
            "Luxer One lockers", "Pressbox dry cleaning",
        ],
        "unit_features": [
            "10ft ceilings", "Whirlpool appliances", "Pearl quartz counters",
            "Integrated spice racks", "Custom modular closets", "USB ports",
        ],
        "parking_type": "Garage",
        "pet_friendly": True,
        "doorman_concierge": False,
        "pool": False,
        "rooftop": True,
        "fitness": "Premium/Top-floor",
    },
    "westerly": {
        "building_amenities": [
            "Rooftop pool", "Hot tub", "Cabanas", "Party room",
            "Coworking pods", "Coffee bar", "Dog run", "Pet spa",
        ],
        "unit_features": [
            "Quartz countertops", "Hardwood floors",
            "Floor-to-ceiling windows", "In-unit W/D", "Large closets",
        ],
        "parking_type": "Garage",
        "pet_friendly": True,
        "doorman_concierge": True,
        "pool": True,
        "rooftop": True,
        "fitness": "Premium + Yoga studio",
    },
    "hugo-river-north": {
        "building_amenities": [
            "2nd floor pool deck", "Poolside cabanas",
            "10th floor amenity deck", "Co-working spaces",
            "Dog park", "Pet spa", "24-hour maintenance",
        ],
        "unit_features": [
            "Industrial aesthetic", "Keyless entry",
            "Quartz/Granite counters", "Walk-in closets",
            "In-unit W/D", "Private balconies",
        ],
        "parking_type": "Assigned garage",
        "pet_friendly": True,
        "doorman_concierge": True,
        "pool": True,
        "rooftop": True,
        "fitness": "Premium (Two gyms)",
    },
    "812-west-adams": {
        "building_amenities": [
            "6,000 sq ft rooftop", "ButterflyMX intercom",
            "HD Surveillance", "Bike storage", "EV charging",
        ],
        "unit_features": [
            "Private balcony/terrace (all units)", "10-12ft ceilings",
            "Samsung appliances", "Waterfall islands",
            "Sound-protected windows", "Custom carved doors",
        ],
        "parking_type": "Heated garage w/ EV",
        "pet_friendly": True,
        "doorman_concierge": False,
        "pool": False,
        "rooftop": True,
        "fitness": "Basic",
    },
    "the-jax": {
        "building_amenities": [
            "Rooftop terrace", "Skyline lounge",
            "Dog run (9th floor)", "Bike workshop",
            "Resident lounge", "Demo kitchen",
        ],
        "unit_features": [
            "Hardwood-style floors", "Quartz countertops", "Gas ranges",
            "In-unit W/D", "Large walk-in closets",
        ],
        "parking_type": "Garage",
        "pet_friendly": True,
        "doorman_concierge": False,
        "pool": False,
        "rooftop": True,
        "fitness": "Basic/Top-floor",
    },
    "the-ardus": {
        "building_amenities": [
            "Happy Monday Cafe in lobby", "Rooftop lounge",
            "Pool table", "Sun loungers", "Grilling stations",
            "FLATS Fit gym", "Dry cleaning",
        ],
        "unit_features": [
            "Industrial-chic", "Glazed concrete or hardwood",
            "Subway tile", "Soft-close cabinets",
            "Rain showers", "10-12ft ceilings",
        ],
        "parking_type": "Street/Limited garage",
        "pet_friendly": True,
        "doorman_concierge": True,
        "pool": False,
        "rooftop": True,
        "fitness": "Premium/FLATS Fit",
    },
    "evo-union-park": {
        "building_amenities": [
            "Oversized pool", "Poolside cabanas", "Gaming room",
            "Co-working lounge", "Dog run", "Pet spa", "EV charging",
        ],
        "unit_features": [
            "Exposed concrete ceilings", "French door refrigerators",
            "Wine fridges (select)", "Bluetooth shower heads",
            "Nest thermostats", "Latch keyless entry",
        ],
        "parking_type": "Integrated garage w/ EV",
        "pet_friendly": True,
        "doorman_concierge": True,
        "pool": True,
        "rooftop": True,
        "fitness": "Premium/Technogym",
    },
    "arthurs-of-old-town": {
        "building_amenities": [
            "Enormous rooftop deck", "Shared workspaces",
            "24/7 coffee bar", "On-site dog park",
            "Dog wash station", "Storage lockers",
        ],
        "unit_features": [
            "Oak-toned vinyl plank", "Exposed concrete",
            "European cabinetry", "In-unit W/D",
            "Custom built-in shelving",
        ],
        "parking_type": "Garage",
        "pet_friendly": True,
        "doorman_concierge": False,
        "pool": False,
        "rooftop": True,
        "fitness": "Basic + Yoga studio",
    },
    "the-van-buren": {
        "building_amenities": [
            "Rooftop pool", "Private cabanas",
            "4,000 sq ft terrace", "Indoor dog run",
            "Pet spa", "Guest suite", "Catering kitchen",
        ],
        "unit_features": [
            "Wide-plank flooring", "Nest thermostats", "Keyless entry",
            "Quartz counters", "Floor-to-ceiling windows",
            "Walk-in closets",
        ],
        "parking_type": "Attached garage",
        "pet_friendly": True,
        "doorman_concierge": True,
        "pool": True,
        "rooftop": True,
        "fitness": "Premium + Yoga studio",
    },
    "spoke-apartments": {
        "building_amenities": [
            "Rooftop pool and hydrotherapy spa",
            "Sky lounge with private terrace and chef-grade kitchen",
            "24-hour fitness center with boxing system",
            "Two private training studios (yoga/fitness)",
            "Virtual cycling studio with Peloton bikes",
            "The Venue (performance space with stage and custom sound)",
            "Recording studio", "Interactive game room",
            "Outdoor bocce ball court",
            "Coworking spaces and conference room",
            "Heated dog run and deluxe dog spa",
            "Indoor bike storage and dedicated bike shop",
            "Guest suite",
        ],
        "unit_features": [
            "Quartz countertops", "Stainless steel appliances",
            "Gas slide-in ranges", "Kitchen islands (select units)",
            "Hardwood-style flooring", "In-unit W/D",
            "Walk-in closets with Elfa shelving",
            "Floor-to-ceiling windows",
        ],
        "parking_type": "On-site garage (with guest parking)",
        "pet_friendly": True,
        "doorman_concierge": True,
        "pool": True,
        "rooftop": True,
        "fitness": "24/7 fitness center, yoga studios, and virtual cycling",
    },
    "avenir-apartments": {
        "building_amenities": [
            "Landscaped roof terrace with pool and whirlpool",
            "Poolside cabanas, fire pits, and grilling stations",
            "24/7 state-of-the-art fitness center",
            "Yoga studio and group exercise space",
            "Indoor basketball court", "Maker Space for creative projects",
            "Co-working lounge and business suite",
            "On-site Gallery Café in lobby",
            "Luxor One package system", "TideSpin dry cleaning",
            "On-site dog run and dog spa", "Reservable guest suite",
        ],
        "unit_features": [
            "Full-size in-unit W/D",
            "Stainless steel GE appliances with ice makers",
            "Full-height porcelain backsplashes", "Wide plank flooring",
            "Linear LED pendant lighting", "Custom roller shades",
            "Floor-to-ceiling windows",
            "Smart Suite by Ori expandable furniture (select studios)",
            "Private balconies (select units)",
        ],
        "parking_type": "Private on-site garage with EV charging",
        "pet_friendly": True,
        "doorman_concierge": True,
        "pool": True,
        "rooftop": True,
        "fitness": "24/7 fitness center, yoga studio, and basketball court",
    },
}
